### ISSUE TITLE
Using non final class Decodable

### ISSUE THREAD

**Issue by marcmatta** [ikesyo/Himotoki#118]
I have an issue since i last updated my pods and Himotoki got upgraded to 2.0.0.

I no longer can use DecodedType and I have the following scenario I'd appreciate if you can help me fix.

I am subclassing a class which I need to be decodable like such:

```
class A: Decodable {
    var type : Int = 0
    var title: String = ""

    init (e: Extractor) {
        type = try! e <| "type"
        title = try! e <| "title"
    }

    static func decode(e: Extractor) throws -> A {
        let type : Int = try e <| "type"
        switch type {
        case 0:
            return B(e: e)
        case 1:
            return C(e: e)
        case 2:
            return A(e: e)
        }
    }
}

class B: A {
    var total : Double = 0.0
    override init(e: Extractor) {
        total = try! e <| "total"
        super.init(e: e)
    }
}

class C: A {
    var link : String = ""
    override init(e: Extractor) {
        link = try! e <| "link"
        super.init(e: e)
    }
}
```

I now have a compiler error on this line **static func decode(e: Extractor) throws -> A** which says Method 'decode' in non-final class 'A' must return 'Self' to conform to protocol 'Decodable'

Thank you for your help in advance! Great library :+1: !

**Comment by ikesyo** [comment]
I'm sorry for the inconvenience. I'm reconsidering about `DecodedType` associatedtype and the class cluster pattern you described here: #122

**Comment by tarunon** [comment]
I guess we can use `castOrFail` function in this case.
https://github.com/ikesyo/Himotoki/blob/a1d9dfe010c841a383ff6f68df69248c9ff6f725/Sources/StandardLib.swift#L89-L95
And new `decode` function is,

``` swift
static func decode(e: Extractor) throws -> Self {
    let type : Int = try e <| "type"
    switch type {
    case 0:
        return try castOrFail(B(e: e))
    case 1:
        return try castOrFail(C(e: e))
    case 2:
        return try castOrFail(A(e: e))
    }
}
```

I believe it would work well.

**Comment by marcmatta** [comment]
okay thanks for your help!

**Comment by ikesyo** [comment]
I'm sorry for the late response. I'm convinced that make `castOrFail` function `public` should be good enough for now.
