### ISSUE TITLE
Nested params

### ISSUE THREAD

**Issue by nghialv** [ikesyo/Himotoki#12]
Thanks for your great lib. How can i extract nested params. For example, i want to get the value of `name` in `owner`.

``` swift
e <| "owner,name"
```

**Comment by ikesyo** [comment]
Thanks for your attention and the question!

I don't mention about it in the README yet, but you can achieve that by the following way (just like a key path representation in Objective-C):

``` swift
e <| "owner.name"
```

This is the same way as [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper).

**Comment by nghialv** [comment]
Great! Thank you very much.

**Comment by nghialv** [comment]
@ikesyo Himotoki is so cool. I'm using it in my demo app.
https://github.com/nghialv/Future/blob/master/DemoApp/DemoApp/Model.swift

Thanks for your working.

**Comment by ikesyo** [comment]
@nghialv [Himotoki 0.4](https://github.com/ikesyo/Himotoki/releases/tag/0.4) now uses a new `KeyPath` type with `ArrayLiteralConvertible`, instead of a key path representation. So you should write `e <| [ "owner", "name" ]` after this.

Sorry for the inconvenience! :bow:
