### ISSUE TITLE
default implementation for enums that have a raw string value

### ISSUE THREAD

**Issue by AndrewSB** [ikesyo/Himotoki#153]
It would be awesome for enum's that have a rawValue String to have implicit conformance to Decodable. If you think it's a good idea @ikesyo, I can go ahead and start a PR 😄

**Comment by ikesyo** [comment]
This is it: https://github.com/ikesyo/Himotoki/blob/3.0.0/Sources/RawRepresentable.swift. You just need to declare `Decodable` conformance:

``` swift
enum YourEnum: String, Decodable {
    case A, B, C
}
```
