### ISSUE TITLE
valueOptional triggers swift exception break point

### ISSUE THREAD

**Issue by gilpolak** [ikesyo/Himotoki#162]
When calling valueOptional with a value that might return null,
 `value` method is called, `value` tries to decode a given keyPath, if the keyPath is null(which is logically correct since I called valueOptional),
`value` throws on `DecodeError.missingKeyPath`, which triggers swift exception break point.

Is there any future plans in solving this issue? maybe leading valueOptional through a different end point?

**Comment by ikesyo** [comment]
Thanks for filing the issue @gilpolak!

I opened #163 to address this. Could you please try that branch?
