### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by neoneye** [ikesyo/Himotoki#170]
It unclear from the [README.md](https://github.com/ikesyo/Himotoki/blob/master/README.md) if Himotoki runs on Linux.

I have browsed around in the code and it mentions Linux several places.

Perhaps make it more clear that Linux is supported.

**Comment by ikesyo** [comment]
Did you see [the release note](https://github.com/ikesyo/Himotoki/releases/tag/3.0.0)?

Anyway the README should be updated to reflect Linux and SwiftPM support. Thanks for bringing this up!

**Comment by neoneye** [comment]
Thank you @ikesyo, I didn't look at the release notes.
