### ISSUE TITLE
How best to extract raw dictionaries?

### ISSUE THREAD

**Issue by dcaunt** [ikesyo/Himotoki#171]
I have some JSON where one key path returns an `Array<Dictionary<String,Any>>`, that is an array of `[String:Any]` and I want to pass this to a `Transformer` for manipulation into a different structure. 

The issue I have is that `Extractor`'s  `array` and `arrayOptional` methods expect to return an array of `Decodable` `T`. I can see why this works for `Transformer<String, URL>` and the like thanks to the extensions in `StandardLib.swift`, but `[String:Any]` does not conform to `Decodable`.

The only way I can get this to work is by adding an extension on Dictionary as follows:

```
extension Dictionary: Decodable {
    public static func decode(_ e: Extractor) throws -> Dictionary<Key, Value> {
        return try castOrFail(e.rawValue)
    }
}
```

Is this correct? Should this be part of `StandardLib.swift`, or am I approaching this in the wrong way?

**Comment by danielmhanover** [comment]
+1

**Comment by dcaunt** [comment]
I figured this out with a little help from [#149 (comment)](https://github.com/ikesyo/Himotoki/issues/149#issuecomment-247234104). As `Extractor` implements `Decodable`, we can retrieve a collection and map as described:

```
let extractors: [String:Extractor] = e <|-| "some_key"
```
