### ISSUE TITLE
Why Class can not  decode by Himotoki?

### ISSUE THREAD

**Issue by hjw6160602** [ikesyo/Himotoki#178]
Why Class in Swift can not  decode by Himotoki?
such as :
class Hello: Decodable {
    var text: String?
}

static func decode(_ e: Extractor)  throws -> UserModel {
        return try UserModel (
            text  : e <|  "text",
        )
}

**Comment by dcaunt** [comment]
Classes don't have memberwise initalizers by default. You have to implement an initializer for your class and then you can call it in `decode`.

**Comment by ikesyo** [comment]
Thanks @dcaunt!
