### ISSUE TITLE
Why not serialization ?

### ISSUE THREAD

**Issue by klefevre** [ikesyo/Himotoki#67]
Hi, I really appreciate your library but I can't use it in current project because it doesn't support serialization. You seem don't want to had this feature in next releases. But why ? It would definitively be a good feature.

**Comment by ikesyo** [comment]
Hi, thank you for the message! How about adding your implementation like this?

``` swift
extension YourModel {
    func encode() -> AnyObject {
        return [
            "foo": self.foo,
            "bar": self.bar,
            "baz": self.baz.encode(),
            ...
        ]
    }
}
```

Since this library does not have mutable stuffs and not use reflection APIs, there is not so much thing for serialization support, I think. Something like https://github.com/edwardaux/Ogra might be a direction.

**Comment by klefevre** [comment]
Thanks for your answer. Indeed, I guess this way of doing serialization might be enough for my use cases.
Tests serializations that way was bit hard to wrote since testing AnyObject vs AnyObject isn't really straightforward.
Maybe the Argo/Ogra way of creating a JSON object instead of AnyObject is a good way to go...
Once again, thanks for answer.
