### ISSUE TITLE
Crash when nested object is not a dictionary

### ISSUE THREAD

**Issue by nakiwo** [ikesyo/Himotoki#70]
In Himotoki 1.3.0 release.
decode function crashes when nested object is not a dictionary.

``` swift
struct Group: Decodable {
    let locationName: String

    static func decode(e: Extractor) throws -> Group {
        return try Group(
            locationName: e <| [ "location", "name" ] // Parse nested objects
        )
    }
}

func test() {
    var JSON: [String: AnyObject] = [
        "location" : "foo",
    ]

    do {
        let g: Group = try decode(JSON) // crash
    } catch ...
}
```

It seems valueFor function (in Extractor.swift) assumes 'object' parameter is a dictionary.
In above example, string "foo" is passed as 'object' parameter then crash.

**Comment by ikesyo** [comment]
Thank you for the report! I've confirmed that bug and will fix it soon. :bow:

**Comment by nakiwo** [comment]
👍
