### ISSUE TITLE
Foundation dependency

### ISSUE THREAD

**Issue by loretoparisi** [ikesyo/Himotoki#80]
:+1: for this project! I'm going to add to my https://github.com/loretoparisi/ios-json-benchmark JSON comparison project.
I have a question. In terms of `pure swift language`, using Apple's `Foundation` creates a dependency from `Cocoa`. Any way to get rid of it (no `Cocoa` dependencies at all).
Thank you.

**Comment by loretoparisi** [comment]
Specifically looking at the `Sources` I can see only those three dependencies:

(Extractor.swift)

``` Swift
import class Foundation.NSDictionary
import class Foundation.NSNull
```

(NSNumber.swift)

``` swift
import class Foundation.NSNumber
```

**Comment by ikesyo** [comment]
Thanks for your interest to this! :smile: 

> I have a question. In terms of pure swift language, using Apple's Foundation creates a dependency from Cocoa. Any way to get rid of it (no Cocoa dependencies at all).

`Foundation` is now being implemented in Swift here: https://github.com/apple/swift-corelibs-foundation/. So using `Foundation` does not mean depending on Cocoa.

I'm trying to add Linux support for this library now.

**Comment by loretoparisi** [comment]
@ikesyo :+1: great, this opens to a pure Swift code library in the next. Amazing.

**Comment by ikesyo** [comment]
Swift 3.0 is finally released with swift-corelibs-foundation: https://swift.org/blog/swift-3-0-released/

🎉

**Comment by loretoparisi** [comment]
@ikesyo that is an amazing news!!!
