### ISSUE TITLE
Help Parsing Objects

### ISSUE THREAD

**Issue by marcmatta** [ikesyo/Himotoki#85]
Hi,

Can you please help me with the following scenario?

I have a base object of type BaseObj like follows:

``` swift
struct BaseObj {
   let type: Int
}
```

and other classes that inherit from this one

``` swift
struct ObjA: BaseObj {
   let title: String
}

struct ObjB: BaseObj {
   let description: String 
}
```

my JSON looks like follows: 

``` json
{  
   "objects":[  
      {  
         "type":1,
         "title":"test title"
      },
      {  
         "type":2,
         "description":"test description"
      }
   ]
}
}
```

I would like my parser to return an array of BaseObj objects correctly initialized based on the type.

How would you go about parsing this response?

I would very much appreciate your help!

Thanks in advance.

**Comment by ikesyo** [comment]
Are you referring to `class` but `struct`? `struct` cannot be extended.

I would write as follows:

``` swift
class BaseObj {
    enum ObjType: Int, Decodable {
        case A = 1, B
    }

    let type: ObjType

    init(type: ObjType) {
        self.type = type
    }
}

class ObjA: BaseObj {
    let title: String

    init(title: String) {
        self.title = title
        super.init(type: .A)
    }
}

class ObjB: BaseObj {
    let description: String

    init(description: String) {
        self.description = description
        super.init(type: .B)
    }
}

extension BaseObj: Decodable {
    static func decode(e: Extractor) throws -> BaseObj {
        let type: BaseObj.ObjType = try e <| "type"
        switch type {
        case .A: return ObjA(title: try e <| "title")
        case .B: return ObjB(description: try e <| "description")
        }
    }
}
```

**Comment by marcmatta** [comment]
yes you're absolutely right about structs I haven't noticed that because I went and copy/pasted my question.

Thank you for the solution :+1: I will give it a try and I will let you know how it goes.

Great lib btw; Simple yet elegant
